name: traffic_sign_recognition
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - numpy=1.21.2
  - matplotlib=3.4.3
  - pandas=1.3.4
  - Pillow=8.4.0
  - pytorch-ranger=0.1.1
  - PyYAML=6.0
  - ray-tune=1.6.0
  - scikit-image=0.17.2
  - scikit-learn=1.0.1
  - scikit-optimize=0.8.1
  - seaborn=0.11.2
  - tensorboardX=2.4
  - pytorch=1.10.0
  - torch-optimizer=0.3.0
  - torchmetrics=0.6.0
  - torchvision=0.11.1
  - tqdm=4.62.3
  - cudatoolkit=11.3
  - notebook
  - pip:
      - hyperopt==0.2.5
      - pytorch-ranger==0.1.1
      - torch-optimizer==0.3.0
      - bayesian-optimization
      - hpbandster
      - ConfigSpace
      - flaml
      - dragonfly-opt
      - HEBO
      - nevergrad
      - scikit-optimize
