name: traffic_sign_recognition
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - cudnn
  - ipython
  - matplotlib
  - notebook
  - numpy
  - opencv
  - pandas
  - pillow
  - pip
  - python=3.9
  - pytorch=1.10
  - pyyaml
  - ray-tune=1.6.0
  - scikit-learn
  - scipy
  - tensorboard
  - tensorboardx
  - tensorflow-estimator
  - tensorflow-gpu
  - torchvision=0.11
  - torchmetrics
  - tqdm
  - yaml
  - pip:
    - cloudpickle==2.0.0
    - future==0.18.2
    - hyperopt==0.2.5
    - networkx==2.6.3
    - pytorch-ranger==0.1.1
    - torch-optimizer==0.3.0
    - torchgeometry==0.1.2
    - bayesian-optimization
    - hpbandster
    - ConfigSpace
    - flaml
    - dragonfly-opt
    - HEBO
    - hyperopt
    - nevergrad
prefix: /home/albert/anaconda3/envs/traffic_sign_recognition
